[package]
authors.workspace = true
categories = ["command-line-utilities", "development-tools"]
description = "Git plugin for managing worktrees"
edition.workspace = true
homepage.workspace = true
keywords = ["cli", "git", "worktree", "workon"]
license.workspace = true
name = "git-workon"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.13.0"
include = [
  "build.rs",
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
]

[features]
vendored = ["git-workon-lib/vendored", "git2/vendored-libgit2", "git2/vendored-openssl"]

[dependencies]
clap.workspace = true
clap-verbosity-flag.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
dialoguer.workspace = true
env_logger.workspace = true
indicatif.workspace = true
git-workon-lib.workspace = true
git2.workspace = true
glob.workspace = true
log.workspace = true
miette.workspace = true
serde_json.workspace = true
owo-colors.workspace = true
fuzzy-matcher.workspace = true
pathdiff.workspace = true
supports-color.workspace = true
unicode-width.workspace = true

[package.metadata.dist]
include = [
  "dist/git-workon.1",
  "dist/git-workon.bash",
  "dist/_git-workon",
  "dist/git-workon.fish",
]

[dev-dependencies]
assert_cmd.workspace = true
assert_fs.workspace = true
git2.workspace = true
git-workon-fixture.workspace = true
expectrl.workspace = true
predicates.workspace = true

[build-dependencies]
clap.workspace = true
clap-verbosity-flag.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
