[package]
authors.workspace = true
categories = ["development-tools", "command-line-utilities"]
description = "API for managing worktrees"
edition.workspace = true
homepage.workspace = true
keywords = ["git", "worktree", "workon"]
license.workspace = true
name = "git-workon-lib"
readme = "README.md"
repository.workspace = true
version = "0.9.0"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
]

[lib]
name = "workon"

[features]
vendored = ["git2/vendored-libgit2", "git2/vendored-openssl"]

[dependencies]
dialoguer.workspace = true
env_logger.workspace = true
git2.workspace = true
auth-git2.workspace = true
glob.workspace = true
ignore.workspace = true
libc.workspace = true
log.workspace = true
miette.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_fs.workspace = true
predicates.workspace = true
git-workon-fixture.workspace = true
serial_test.workspace = true
